# Generated by Django 3.1.2 on 2020-10-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0004_auto_20201013_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('ru', 'RUB'), ('us', 'USD')], default='ru', max_length=2),
        ),
    ]
